#!/usr/bin/env bash
# Build the Android debug APK via the official kivy/buildozer Docker image.
# Run from the project root, in Git Bash (MSYS), with Docker Desktop running.
#
# MSYS_NO_PATHCONV=1 stops Git Bash from mangling the container paths
# (e.g. /home/user/hostcwd, /usr/local/bin/entrypoint.sh) into Windows paths.
#
# The image's default entrypoint chowns its whole home dir recursively,
# which — because the project (with its multi-GB .buildozer SDK/NDK cache)
# is bind-mounted inside that same home dir on a slow Windows drive mount —
# takes forever. We bypass it with --entrypoint bash and call buildozer
# directly, exporting HOME=/home/user so build.py finds the SDK where the
# image expects it (it hardcodes /home/user/.buildozer for the apk step).
#
# If buildozer prompts about running as root, pipe confirmation in:
#   echo y | ./build.sh
#
# The Android SDK/NDK (~/.buildozer inside the container) live in the
# persistent named volume `subscr_buildozer_home`, not in the project's own
# .buildozer (that only holds the compiled recipes/dist, which IS bind-mounted
# from this repo). Without this volume every container run starts with an
# empty SDK dir and has to re-download everything from scratch each time.
#
# The debug signing key (debug.keystore, auto-generated by Gradle on first
# use) also lives in a persistent volume, `subscr_android_home`. Without it,
# every container run gets a fresh random debug key, and Android refuses to
# install a new APK over an existing install signed with a different key
# ("app not installed as package conflicts with an existing package").
# Persisting it means every build after the first reuses the same key, so
# reinstalling over the old app just works.
#
# NOTE: this is mounted at /root/.android, not /home/user/.android. Despite
# exporting HOME=/home/user for buildozer's own process, the actual gradlew
# subprocess it shells out to resolves user.home back to /root (confirmed by
# its Gradle downloads landing in /root/.gradle, not /home/user/.gradle) -
# so that's where the keystore actually gets written.
#
# Same reasoning applies to the Gradle distribution/dependency cache itself
# (/root/.gradle) - without persisting it, every build re-downloads the ~200MB
# Gradle distribution zip from scratch.

set -e
docker volume create subscr_buildozer_home >/dev/null
docker volume create subscr_android_home >/dev/null
docker volume create subscr_gradle_home >/dev/null
MSYS_NO_PATHCONV=1 docker run --rm -i -v "$(pwd)":/home/user/hostcwd \
    -v subscr_buildozer_home:/home/user/.buildozer \
    -v subscr_android_home:/root/.android \
    -v subscr_gradle_home:/root/.gradle \
    --entrypoint bash kivy/buildozer -c \
    "export HOME=/home/user && cd /home/user/hostcwd && /home/user/.venv/bin/buildozer android debug"
